apiVersion: v1
kind: Service
metadata:
  name: db-postgres-service
  labels:
    type: db
spec:
  type: NodePort
  selector:
    type: db
    app: db-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
