apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    type: db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
