apiVersion: v1
kind: Service
metadata:
  name: gamesession-api-service
spec:
  type: NodePort
  selector:
    app: gamesession-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
